apiVersion: v1
kind: Service
metadata:
  name: memcached2
spec:
  ports:
  - port: 11211 
  selector:
    app: memcached2 
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached2
spec:
  selector:
    matchLabels:
      app: memcached2
  template:
    metadata:
      labels:
        app: memcached2
    spec:
      restartPolicy: Always
      hostname: memcached2
      containers:
      - name: memcached2-ct
        image: memcached:1.5-alpine
        ports:
        - containerPort: 11211 
        args: ["memcached", "-m", "256"]
