apiVersion: v1
kind: Service
metadata:
  name: memcached-single
spec:
  ports:
  - port: 3306
  selector:
    app: memcached-single
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-single
spec:
  selector:
    matchLabels:
      app: memcached-single
  template:
    metadata:
      labels:
        app: memcached-single
    spec:
      restartPolicy: Always
      hostname: memcached-single
      containers:
      - name: memcached-single-ct
        image: memcached:1.5-alpine
        ports:
        - containerPort: 11211 
          hostPort: 11211
        args: ["memcached", "-m", "128"]
