apiVersion: v1
kind: Service
metadata:
  name: memcached1
spec:
  ports:
  - port: 11211 
  selector:
    app: memcached1 
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached1
spec:
  selector:
    matchLabels:
      app: memcached1
  template:
    metadata:
      labels:
        app: memcached1
    spec:
      restartPolicy: Always
      hostname: memcached1
      containers:
      - name: memcached1-ct
        image: memcached:1.5-alpine
        ports:
        - containerPort: 11211 
        args: ["memcached", "-m", "256"]
